# Generated by Django 4.2.5 on 2024-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quizsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="answered_questions",
            field=models.JSONField(default=list),
        ),
    ]
