# Generated by Django 4.2.5 on 2024-12-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizsession_answered_questions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="option1", new_name="option_1",
        ),
        migrations.RenameField(
            model_name="question", old_name="option2", new_name="option_2",
        ),
        migrations.RenameField(
            model_name="question", old_name="option3", new_name="option_3",
        ),
        migrations.RenameField(
            model_name="question", old_name="option4", new_name="option_4",
        ),
        migrations.RenameField(
            model_name="question", old_name="text", new_name="question_text",
        ),
        migrations.RenameField(
            model_name="quizsession",
            old_name="correct_answer",
            new_name="correct_answers",
        ),
        migrations.RenameField(
            model_name="quizsession",
            old_name="question_answered",
            new_name="incorrect_answers",
        ),
        migrations.RemoveField(model_name="quizsession", name="answered_questions",),
    ]
