# Generated by Django 4.2.5 on 2024-12-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_rename_option1_question_option_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="option_1", new_name="option_a",
        ),
        migrations.RenameField(
            model_name="question", old_name="option_2", new_name="option_b",
        ),
        migrations.RenameField(
            model_name="question", old_name="option_3", new_name="option_c",
        ),
        migrations.RenameField(
            model_name="question", old_name="option_4", new_name="option_d",
        ),
        migrations.RemoveField(model_name="question", name="correct_option",),
        migrations.RemoveField(model_name="quizsession", name="correct_answers",),
        migrations.RemoveField(model_name="quizsession", name="end_time",),
        migrations.RemoveField(model_name="quizsession", name="incorrect_answers",),
        migrations.RemoveField(model_name="quizsession", name="start_time",),
        migrations.RemoveField(model_name="quizsession", name="total_questions",),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="na", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizsession",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="question",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizsession",
            name="selected_answer",
            field=models.CharField(
                choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                default="na",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
